# Generated by Django 5.0.3 on 2024-03-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255, verbose_name='house number')),
                ('floor', models.IntegerField(default=1, verbose_name='floor')),
                ('area', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='area')),
                ('datetime_of_public', models.DateTimeField(auto_now=True, verbose_name='datetime of public')),
                ('date_of_public', models.DateField(auto_now=True, verbose_name='date of public')),
                ('status', models.CharField(max_length=255, verbose_name='status')),
                ('price', models.BigIntegerField(verbose_name='price')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.company')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
    ]
