# Generated by Django 5.0.3 on 2024-03-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_of_client', models.CharField(max_length=100, verbose_name='fullname of client')),
                ('phone_number_of_client', models.CharField(max_length=20, verbose_name='phone number of client')),
                ('date_of_create', models.DateTimeField(auto_now=True)),
                ('id_of_agreement', models.IntegerField()),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
            },
        ),
    ]
